import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
const GREEN="#70C900";
type LanguageCode = "tr" | "en";
export default function ProfileLanguageScreen(){const [language,setLanguage]=useState<LanguageCode>("tr");return <SafeAreaView style={s.safe}><View style={s.content}><Header title="Dil"/><View style={s.intro}><View style={s.iconCircle}><Ionicons name="globe-outline" size={34} color={GREEN}/></View><Text style={s.introText}>Uygulamada kullanmak istediğin dili seçebilirsin.</Text></View><View style={s.card}><Language label="Türkçe" selected={language==="tr"} onPress={()=>setLanguage("tr")}/><Language label="English" selected={language==="en"} onPress={()=>setLanguage("en")} isLast/></View><Text style={s.note}>Bu seçim geçicidir ve uygulamanın dilini henüz değiştirmez.</Text></View></SafeAreaView>}
function Language({label,selected,onPress,isLast=false}:{label:string;selected:boolean;onPress:()=>void;isLast?:boolean}){return <Pressable onPress={onPress} style={[s.row,!isLast&&s.border]}><View style={[s.radio,selected&&s.radioSelected]}>{selected?<View style={s.dot}/>:null}</View><Text style={s.label}>{label}</Text></Pressable>}
function Header({title}:{title:string}){return <View style={s.header}><Pressable onPress={()=>router.replace("/(main)/profile")} style={s.back}><Ionicons name="chevron-back" size={22} color={GREEN}/></Pressable><Text style={s.headerTitle}>{title}</Text><View style={{width:38}}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F8F9F4"},content:{padding:20,paddingTop:14},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:28},back:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:"#A8D96D",alignItems:"center",justifyContent:"center",backgroundColor:"#FFF"},headerTitle:{fontSize:19,fontWeight:"900",color:"#202320"},intro:{flexDirection:"row",alignItems:"center",marginBottom:28},iconCircle:{width:66,height:66,borderRadius:33,alignItems:"center",justifyContent:"center",backgroundColor:"#EAF6D7"},introText:{flex:1,marginLeft:17,fontSize:13,lineHeight:19,color:"#4F534E"},card:{overflow:"hidden",borderWidth:1,borderColor:"#DDE2D8",borderRadius:20,backgroundColor:"#FFF"},row:{height:65,flexDirection:"row",alignItems:"center",paddingHorizontal:18},border:{borderBottomWidth:1,borderBottomColor:"#E2E5DF"},radio:{width:21,height:21,borderRadius:11,borderWidth:1.5,borderColor:"#777",alignItems:"center",justifyContent:"center"},radioSelected:{borderColor:GREEN},dot:{width:11,height:11,borderRadius:6,backgroundColor:GREEN},label:{marginLeft:13,fontSize:15,color:"#202320"},note:{marginTop:14,fontSize:11,color:"#858985",textAlign:"center"}});
