import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
const GREEN="#70C900";
type ThemeChoice = "light" | "dark";
export default function ProfileAppSettingsScreen(){const [theme,setTheme]=useState<ThemeChoice>("light");return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Header title="Uygulama Ayarları"/><View style={s.intro}><View style={s.iconCircle}><Ionicons name="settings-outline" size={34} color={GREEN}/></View><Text style={s.introText}>Uygulama deneyimini kendi tercihlerine göre özelleştir.</Text></View><View style={s.card}><Text style={s.label}>Tema</Text><View style={s.segment}><Option text="Açık" selected={theme==="light"} onPress={()=>setTheme("light")}/><Option text="Koyu" selected={theme==="dark"} onPress={()=>setTheme("dark")}/></View></View><Text style={s.note}>Bu seçim geçicidir ve uygulamanın temasını henüz değiştirmez.</Text></ScrollView></SafeAreaView>}
function Option({text,selected,onPress}:{text:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.option,selected&&s.selected]}><Text style={[s.optionText,selected&&s.selectedText]}>{text}</Text></Pressable>}
function Header({title}:{title:string}){return <View style={s.header}><Pressable onPress={()=>router.replace("/(main)/profile")} style={s.back}><Ionicons name="chevron-back" size={22} color={GREEN}/></Pressable><Text style={s.headerTitle}>{title}</Text><View style={{width:38}}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F8F9F4"},content:{padding:20,paddingTop:14,paddingBottom:30},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:28},back:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:"#A8D96D",alignItems:"center",justifyContent:"center",backgroundColor:"#FFF"},headerTitle:{fontSize:19,fontWeight:"900",color:"#202320"},intro:{flexDirection:"row",alignItems:"center",marginBottom:28},iconCircle:{width:66,height:66,borderRadius:33,alignItems:"center",justifyContent:"center",backgroundColor:"#EAF6D7"},introText:{flex:1,marginLeft:17,fontSize:13,lineHeight:19,color:"#4F534E"},card:{padding:16,borderWidth:1,borderColor:"#DDE2D8",borderRadius:20,backgroundColor:"#FFF"},label:{marginBottom:10,fontSize:13,color:"#202320"},segment:{height:42,flexDirection:"row",overflow:"hidden",borderWidth:1,borderColor:"#DDE2D8",borderRadius:10,backgroundColor:"#F5F6F4"},option:{flex:1,alignItems:"center",justifyContent:"center"},selected:{borderWidth:1,borderColor:GREEN,borderRadius:9,backgroundColor:"#F7FCEB"},optionText:{fontSize:13,color:"#555"},selectedText:{color:"#202320",fontWeight:"700"},divider:{height:1,marginVertical:18,backgroundColor:"#E2E5DF"},select:{height:43,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:13,borderWidth:1,borderColor:"#DDE2D8",borderRadius:10},selectText:{fontSize:14,color:"#202320"},cacheRow:{flexDirection:"row",alignItems:"center"},cacheTitle:{fontSize:14,color:"#202320"},cacheDescription:{maxWidth:260,marginTop:5,fontSize:11,lineHeight:16,color:"#777"},note:{marginTop:14,fontSize:11,color:"#858985",textAlign:"center"}});
