import type {
  DailyPlanTemplate,
  Exercise,
  ExerciseCategory,
  ExerciseRecordTemplate,
} from "@/shared/lib/home-dashboard";

export const MOCK_EXERCISE_CATEGORIES: ExerciseCategory[] = [
  { id: "chest", name: "Göğüs", icon: "body-outline" },
  { id: "back", name: "Sırt", icon: "body-outline" },
  { id: "legs", name: "Bacak", icon: "walk-outline" },
  { id: "shoulders", name: "Omuz", icon: "body-outline" },
  { id: "arms", name: "Kol", icon: "barbell-outline" },
  { id: "abs", name: "Karın", icon: "fitness-outline" },
  { id: "waist", name: "Bel", icon: "body-outline" },
  { id: "hips", name: "Kalça", icon: "body-outline" },
  { id: "calves", name: "Baldır", icon: "walk-outline" },
  { id: "forearms", name: "Ön Kol", icon: "barbell-outline" },
  { id: "inner-legs", name: "İç Bacak", icon: "walk-outline" },
  { id: "neck", name: "Boyun", icon: "body-outline" },
  { id: "cardio", name: "Kardiyo", icon: "heart-outline" },
];

export const MOCK_EXERCISES: Exercise[] = [
  {
    id: "dumbbell-press",
    name: "Oturarak Dumbbell Press",
    categoryId: "chest",
    description: "Göğüs kaslarını kontrollü çalıştıran press hareketi.",
    level: "Orta seviye",
    image: "barbell-outline",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    categoryId: "back",
    description: "Sırt kaslarını hedefleyen dikey çekiş hareketi.",
    level: "Başlangıç",
    image: "fitness-outline",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    categoryId: "legs",
    description: "Bacak ve kalça kaslarını çalıştıran squat varyasyonu.",
    level: "Başlangıç",
    image: "walk-outline",
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    categoryId: "shoulders",
    description: "Omuzların yan bölümünü hedefleyen kaldırış.",
    level: "Başlangıç",
    image: "barbell-outline",
  },
  {
    id: "biceps-curl",
    name: "Biceps Curl",
    categoryId: "arms",
    description: "Kol kaslarını hedefleyen fleksiyon hareketi.",
    level: "Başlangıç",
    image: "barbell-outline",
  },
  {
    id: "crunch",
    name: "Crunch",
    categoryId: "abs",
    description: "Karın kaslarını hedefleyen gövde fleksiyonu.",
    level: "Başlangıç",
    image: "fitness-outline",
  },
  {
    id: "side-bend",
    name: "Side Bend",
    categoryId: "waist",
    description: "Bel çevresindeki yan gövde kaslarını çalıştırır.",
    level: "Başlangıç",
    image: "body-outline",
  },
  {
    id: "hip-bridge",
    name: "Hip Bridge",
    categoryId: "hips",
    description: "Kalça kaslarını hedefleyen köprü hareketi.",
    level: "Başlangıç",
    image: "body-outline",
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    categoryId: "calves",
    description: "Baldır kaslarını hedefleyen yükselme hareketi.",
    level: "Başlangıç",
    image: "walk-outline",
  },
  {
    id: "wrist-curl",
    name: "Wrist Curl",
    categoryId: "forearms",
    description: "Ön kol kaslarını çalıştıran bilek fleksiyonu.",
    level: "Orta seviye",
    image: "barbell-outline",
  },
  {
    id: "sumo-squat",
    name: "Sumo Squat",
    categoryId: "inner-legs",
    description: "İç bacakları hedefleyen squat varyasyonu.",
    level: "Orta seviye",
    image: "walk-outline",
  },
  {
    id: "neck-mobility",
    name: "Boyun Mobilitesi",
    categoryId: "neck",
    description: "Boyun hareket açıklığını destekleyen mobilite serisi.",
    level: "Başlangıç",
    image: "body-outline",
  },
  {
    id: "jumping-jack",
    name: "Jumping Jack",
    categoryId: "cardio",
    description: "Tüm vücudu hareket ettiren kardiyo egzersizi.",
    level: "Başlangıç",
    image: "heart-outline",
  },
];

export const MOCK_DAILY_PLAN_TEMPLATES: DailyPlanTemplate[] = [
  { id: "monday-plan", dayOfWeek: 1, exercises: [
    { exerciseId: "dumbbell-press", sets: 4, reps: 10 },
    { exerciseId: "biceps-curl", sets: 3, reps: 12 },
  ] },
  { id: "tuesday-plan", dayOfWeek: 2, exercises: [
    { exerciseId: "calf-raise", sets: 3, reps: 15 },
    { exerciseId: "neck-mobility", sets: 2, reps: 10 },
  ] },
  { id: "wednesday-plan", dayOfWeek: 3, exercises: [
    { exerciseId: "lat-pulldown", sets: 4, reps: 10 },
    { exerciseId: "lateral-raise", sets: 3, reps: 15 },
    { exerciseId: "crunch", sets: 3, reps: 15 },
    { exerciseId: "wrist-curl", sets: 2, reps: 12 },
  ] },
  { id: "friday-plan", dayOfWeek: 5, exercises: [
    { exerciseId: "goblet-squat", sets: 4, reps: 12 },
    { exerciseId: "side-bend", sets: 3, reps: 12 },
    { exerciseId: "hip-bridge", sets: 3, reps: 15 },
    { exerciseId: "jumping-jack", sets: 3, reps: 20 },
  ] },
  { id: "sunday-plan", dayOfWeek: 7, exercises: [
    { exerciseId: "sumo-squat", sets: 3, reps: 12 },
    { exerciseId: "calf-raise", sets: 3, reps: 15 },
  ] },
];

export const MOCK_EXERCISE_RECORD_TEMPLATES: ExerciseRecordTemplate[] = [
  { dayOfWeek: 1, exerciseId: "dumbbell-press", status: "completed", completedMovementCount: 10 },
  { dayOfWeek: 1, exerciseId: "biceps-curl", status: "completed", completedMovementCount: 4 },
  { dayOfWeek: 2, exerciseId: "calf-raise", status: "partial", completedMovementCount: 8 },
  { dayOfWeek: 2, exerciseId: "neck-mobility", status: "not_started", completedMovementCount: 0 },
  { dayOfWeek: 3, exerciseId: "lat-pulldown", status: "completed", completedMovementCount: 8 },
  { dayOfWeek: 3, exerciseId: "lateral-raise", status: "completed", completedMovementCount: 6 },
  { dayOfWeek: 3, exerciseId: "crunch", status: "completed", completedMovementCount: 3 },
  { dayOfWeek: 3, exerciseId: "wrist-curl", status: "completed", completedMovementCount: 1 },
  { dayOfWeek: 5, exerciseId: "goblet-squat", status: "completed", completedMovementCount: 9 },
  { dayOfWeek: 5, exerciseId: "side-bend", status: "completed", completedMovementCount: 2 },
  { dayOfWeek: 5, exerciseId: "hip-bridge", status: "completed", completedMovementCount: 2 },
  { dayOfWeek: 5, exerciseId: "jumping-jack", status: "completed", completedMovementCount: 3 },
  { dayOfWeek: 7, exerciseId: "sumo-squat", status: "not_started", completedMovementCount: 0 },
  { dayOfWeek: 7, exerciseId: "calf-raise", status: "not_started", completedMovementCount: 0 },
];
